### ISSUE TITLE
Modular inverse function

### ISSUE THREAD

**Issue by bfcarpio** [folz/math#16]
I've been doing various problems on Advent of Code and day 22's solution can be greatly simplified with the modular inverse function.

From what I have seen, Erlang's math library nor any other library has this function. However, there does seem to be an implementation on [Rosetta Code](https://rosettacode.org/wiki/Modular_inverse#Elixir)

I believe the information above makes a good case as to why this library should have it.

**Comment by Qqwy** [comment]
Having done a couple of things with cryptography in the past, I am aware of the usefulness of a modular inverse function.

Rather than raising an error on failure, I think it would be better to always return an ok/error tuple:

```
@spec mod_inv(num :: int, modulo :: int) :: {:ok, int} | {:error, :not_coprime}`
```

And I think the function should raise an ArgumentError when passed floats, because there is no proper way (in general math) to find the greatest common divisor of two floating point numbers.

**Comment by Qqwy** [comment]
A PR is very welcome :happy: !

_(and if you don't have the time for it, I can give it a shot sometime next week)_

**Comment by bfcarpio** [comment]
I spent about 2 hours just going over the maths if I were to solve the problem by hand. I'll give it a shot, but I'm sure we'll be spending some time getting it to be efficient. I've also found various implementations in C++ that could just be reworked..

As for the tuple idea, I like it. We should have a `mod_inv` and a `mod_inv!` function just to stick with conventions.

**Comment by Qqwy** [comment]
> We should have a mod_inv and a mod_inv! function just to stick with conventions.

:+1: 

>  I'll give it a shot, but I'm sure we'll be spending some time getting it to be efficient.

Perfect! :smile:
