### ISSUE TITLE
missing parentheses are causing nastygrams

### ISSUE THREAD

**Issue by RichMorin** [folz/math#9]
In recent versions of Elixir (eg,  1.5.3), the Math module produces nastygrams about missing parentheses:

```
  warning: variable "description" does not exist and is being expanded to "description()",
  please use parentheses to remove the ambiguity or change the variable name
    /.../deps/math/mix.exs:8
```

**Comment by CraigCottingham** [comment]
Most of these appear to be fixed in `HEAD`. I'll have a PR soon for the rest.

**Comment by CraigCottingham** [comment]
https://github.com/folz/math/pull/11

**Comment by RichMorin** [comment]
Thanks for addressing this.  I also like the fact that you've been trimming off some trailing spaces. Maybe you could reuse some of these to make the doctests prettier and more readable, eg:

    iex>Math.deg2rad(180)
    ---
    iex> Math.deg2rad(180)

**Comment by Qqwy** [comment]
Note that as a contributor of this repository, I am able to merge PRs into HEAD. However, only @folz is able to release new versions of the Hex package.

I have messaged him a couple of days ago in order to ask him to update the `math` library, formally retire it or pass on management of it to someone else. Until now I have not heard back from him.

Until he shows himself, I'll do my best as a contributor to:

-  make sure that the HEAD version of this library does not create warnings on newer elixir versions. 

I will however:

- _not_ merge PRs with new features, because I cannot be sure if that is what @folz would like, and because it will cause HEAD to diverge further and further from the latest version released on Hex.PM. 
- _not_ release new versions of the library to Hex.PM (because I lack the permissions to do so).

**Comment by folz** [comment]
Hi all, getting back from the holiday and catching up on this. Thanks Craig and Rich for the issues and PRs, and Weibe-Martin for following up as a contributor.

As you might have guessed, I haven't had much time to work on this library. I'll admit I'm a little surprised people ended up using it, but here we are. Since I don't want your work to stagnate, my plan is to give @Qqwy release permissions on Hex and generally give them leave to do what's necessary to make the library work well with modern Elixir. I'll follow up with @Qqwy via email.

My personal opinion is that I don't think this library needs much more added to it, since it was originally intended as a convenience wrapper around erlang's `:math`. But, as I'm not using it anymore, I will defer to your judgement for what changes or new features/functions are needed.

**Comment by Qqwy** [comment]
Hey everyone!

I have received permission from @folz to push changes to Hex.PM.

Version 0.3.1 of this library, with changes that do not cause warnings on Elixir 1.7 any more has now been released. :smiley:
